import os

# ── Folder paths ──────────────────────────────────────────
INPUT_DIR  = os.getenv("INPUT_DIR",  "input")
OUTPUT_DIR  = os.getenv("OUTPUT_DIR",  "output")
OUTPUT_FILE = os.getenv("OUTPUT_FILE", "Nile_Pipeline_Issue_Report.xlsx")
SUPPORTED_EXTENSIONS = [".html", ".htm", ".csv", ".xlsx", ".xls"]

# Leave blank → auto-detected from ticket dates each run
REPORT_MONTH_LABEL = os.getenv("REPORT_MONTH_LABEL", "")

COLUMN_ALIASES = {
    "key": ["Issue key", "Key", "Issue Key", "key"],
    "issue_id": ["Issue id", "Issue ID", "ID", "id"],
    "parent_id": ["Parent id", "Parent ID", "Parent", "Parent key"],
    "summary": ["Summary", "summary", "Title"],
    "description": ["Description", "description", "Issue Description"],
    "categories": ["Categories", "categories", "Category", "category", "Catogories", "GSR Category", "GSR Sub Category", "New Categories", "New Catogories", "New Category"],
    "new_categories": ["New Categories", "New Category", "New Catogories", "GSR Sub Category", "GSR Category"],
    "assign": ["Assign", "Assigned To", "Assignee", "assign"],
    "status": ["Status", "status"],
    "created": ["Created", "created", "Date Created", "Created Date"],
    "updated": ["Updated", "updated", "Last Updated", "Updated Date"],
    "assignment_group": ["Assignment Group", "assignment group", "Internal Assignment Group", "Custom field (Assignment Group)"],
    "assignee": ["Assignee", "assignee"],
    "reporter": ["Reporter", "reporter"],
    "resolution": ["Resolution", "resolution"],
    "comments": ["Comments", "comments", "Comment", "customfield_Comments"],
    "close_notes": ["Close Notes", "close notes", "Close Note"],
    "labels": ["Labels", "labels", "Label"],
    "issue_type": ["Issue Type", "Issue type", "issuetype", "Type"],
    "priority": ["Priority", "priority"],
    "inward_cloners": ["Inward issue link (Cloners)"],
    "outward_cloners": ["Outward issue link (Cloners)"],
    "inward_relates": ["Inward issue link (Relates)"],
}

HTML_FIELD_LABELS = {
    "status": ["Status"],
    "issue_type": ["Type", "Issue Type", "GSR Issue Type"],
    "priority": ["Priority"],
    "reporter": ["Reporter"],
    "assignee": ["Assignee"],
    "resolution": ["Resolution"],
    "assignment_group": ["Assignment Group", "Internal Assignment Group"],
    "close_notes": ["Close Notes"],
    "categories": ["Category", "Categories", "GSR Category", "GSR Sub Category"],
    "new_categories": ["New Categories", "GSR Sub Category"],
    "comments": ["Comments"],
    "parent_id": ["Parent", "Parent id", "Parent ID"],
}

CATEGORIES = [
    {
        "name": "Configuration Issue",
        "color": "5B9BD5",
        "keywords": [
            "configuration", "config", "parameter", "setup", "mapping",
            "env issue", "property issue", "config error",
            "configuration issue", "config change", "pipeline config",
            "misconfigured", "config update", "parameter change",
            "pipeline parameter", "wrong config",
            "gwf flag", "gwf eligible", "gwf configured",
            "source data pattern", "source_data_pattern",
            "suspend pipeline", "shut down pipeline", "pipeline suspended",
            "pause pipeline", "paused pipeline",
            "mapping verified", "verify mapping",
            "payer code", "add new payer",
            "decommission pipeline", "decomission pipeline",
            "sftp password", "password needs to be changed",
            "skip ingestion date", "ingestion date skipped",
            "add parameter",
            "published and scheduled",
        ],
    },
    {
        "name": "File Issue",
        "color": "4472C4",
        "keywords": [
            "corrupt file", "invalid file", "encrypted file",
            "damaged file", "empty file", "bad file", "file issue",
            "file not received", "file not found", "file delay",
            "file arrival", "file drop", "source file", "file rejected",
            "file ingestion", "not ingested", "file failure",
            "files failing", "file failing",
            "path does not exist", "file path does not exist",
            "spelling error in filename", "misspelled file name",
            "file name pattern changed", "filename pattern changed",
            "tab names changed", "tab name changed",
            "replacement file received", "replacement files received",
            "file resent", "files resent",
            "reload the files", "please reload",
            "file format changed", "file format update",
            "0 byte file", "zero byte file", "0 byte pgp",
            "same sequence number", "sequence number issue",
            "wrong filename", "wrong file name",
            "picking wrong file", "pick up wrong file",
            "file has been resent", "resend the file",
            "claim extract file", "post pay claim extract",
            "sequence number already used",
            "sequence issue",
            "failed due to sequence",
            "failed for sequence",
            "files failed sequence",
            "awaiting replacement file",
            "requested client to send replacement",
            "waiting for replacement file",
        ],
    },
    {
        "name": "Spooler issue",
        "color": "FF0000",
        "keywords": [
            "spooler", "spoolers", "unscheduled", "stuck",
            "trigger issue", "pickup failure", "spool delay",
            "spool error", "spool failed", "spool queue", "spooling",
            "spoolers failed", "not able to spool",
            "please spool", "spool down",
            "respool", "re-spool", "respooled",
            "ingestion on hold", "ingestion was on hold",
            "not being spooled", "files not spooled",
            "backfill files", "backfill process",
            "files spooled and processed",
            "notouch", "no-touch",
            "proceed the files", "not picking up files",
        ],
    },
    {
        "name": "Data Issue",
        "color": "ED7D31",
        "keywords": [
            "data mismatch", "duplicate data", "null values",
            "incorrect data", "missing records", "data issue",
            "data quality", "wrong data", "data discrepancy",
            "data error", "invalid data", "corrupt data",
            "bad data", "data not matching", "data validation",
            "data integrity", "data drop", "significant data drop",
            "significant data", "unmatched", "raw vs model",
            "claim raw", "0 records to be ingested",
            "causing 0 records", "data ingestion error",
            "date spans showing", "claim date spans",
            "accountnum issue", "accountnum extra digit",
            "extra leading digit", "cannot locate claim",
            "claim not found", "raw data needed",
            "raw data request",
        ],
    },
    {
        "name": "File Missing",
        "color": "FFC000",
        "keywords": [
            "file missing", "files missing", "missing file",
            "no file received", "replacement file pending",
            "missing data file", "not posted", "files not posted",
            "not received", "not seen in cat", "missing history",
            "history files missing", "files are missing",
            "missing dataload", "no touch file",
            "files not seen", "not available in",
            "missing history files",
            "please hold pipeline", "hold pipeline until",
            "waiting on missing files", "cannot locate file",
            "cannot find the file", "no longer able to find",
            "file not arrived", "files not arrived",
            "daily file missing", "weekly file missing",
            "hold until we receive",
        ],
    },
    {
        "name": "Unmatched raw data count",
        "color": "00B050",
        "keywords": [
            "count mismatch", "unmatched count", "raw count mismatch",
            "record mismatch", "unmatched raw data count",
            "record count mismatch", "row count mismatch",
            "raw data count", "unmatched record",
            "unmatched raw counts",
            "lineage report", "file spooled different",
            "count does not match", "count is different",
            "file count mismatch", "different from ftp",
            "nile ftp count", "spooled count different",
        ],
    },
    {
        "name": "Pipeline Schedule",
        "color": "FF8C00",
        "keywords": [
            "pipeline failed", "pipelines failed", "workflow failed",
            "cron issue", "delayed workflow", "dependency issue",
            "schedule", "scheduling", "delayed", "not triggered",
            "cron", "job not triggered", "schedule missed",
            "pipeline not started", "pipeline delay", "late run",
            "got failed", "has failed", "failed for data date",
            "is getting failed", "getting failed",
            "is failing due to", "pipeline is failing",
            "pipeline is currently failing",
            "please fix pipeline", "fix the pipeline",
            "blocking the ingestion", "blocked ingestion",
            "picking two files", "picking unexpected file",
            "convert excel to csv", "convertexceltocsv",
            "shell executor", "shell executer",
            "destination copy failure",
            "permission denied", "user permission denied",
            "failed in stage", "stage failed",
            "history prof failed", "history inst failed",
            "pipeline stopped", "pipeline not running",
            "skip pipeline", "pipeline skip",
            "trigger_bmc_workflow",
            "trigger bmc workflow",
            "bmc pipeline failed",
            "bmc pipeline is failing",
            "bmc pipeline not",
            "trigger_bmc not recognizing",
            "bmc pipelines as it is not",
            "error when running humana bmc",
        ],
    },
    {
        "name": "DB Issue",
        "color": "00B0F0",
        "keywords": [
            "database", "db issue", "sql error", "timeout",
            "oracle", "postgres", "mysql", "db connectivity",
            "db timeout", "database error",
            "disk space", "filegroup", "transaction log",
            "could not allocate", "insufficient disk",
            "sqlserver", "jdbc", "broadcast issue",
            "broadcast timeout", "spark.sql.broadcasttimeout",
            "db writer", "db writer stage",
            "insufficient disk space",
            "database full", "disk full",
            "clear transaction logs", "free up disk space",
            "database admin", "dba request",
            "stuck in db writer", "hive error",
            "hdfs issue", "hadoop issue", "dc-pine",
        ],
    },
    {
        "name": "Metric drop",
        "color": "7030A0",
        "keywords": [
            "metric drop", "low volume", "reduced count",
            "sudden drop", "drop in metrics", "metric decline",
            "volume drop", "low metric",
            "metric percentage drop", "override for metric drop",
            "data metric percentage", "hits threshold",
            "no claim volume", "zero ingested", "0 ingested",
            "record counts low", "count low", "claim volume",
            "zero ingest", "unmated claims",
            "metric drop override", "data metric",
            "claim volume low",
            "zero ingested rows", "0 ingested rows",
            "loading older files past", "claim file count",
        ],
    },
    {
        "name": "Schema issue",
        "color": "FF69B4",
        "keywords": [
            "schema mismatch", "column mismatch", "header mismatch",
            "trailer mismatch", "schema issue", "schema change",
            "schema update", "schema drift", "column missing",
            "field change", "new column", "field missing",
            "schema is not matching", "source file schema",
            "table schema", "check column names", "data-types",
            "layout update", "blank values", "field populating",
            "autoid field", "blank field", "rms field",
            "not matching with the table",
            "mapping validation",
            "layout change", "file layout",
            "sequence length", "appealed line sequence",
            "extra leading digit in field",
            "columns expected", "column count mismatch",
            "par_yn field", "field not being sent",
            "data-types mismatch", "data types mismatch",
        ],
    },
    {
        "name": "Issue Platform",
        "color": "00B0B0",
        "keywords": [
            "nifi", "airflow", "actian", "aws",
            "infrastructure issue", "server issue", "infrastructure",
            "server", "platform", "nifi issue", "airflow issue",
            "actian issue",
            "nile platform issue", "platform issue", "platform problem",
            "infrastructure down", "server down",
            "platform down", "system down",
            "sftp issue", "sftp problem", "sftp error",
            "sftp down", "axway",
            "ftp issue", "ftp error", "ftp problem",
            "ftp down", "connection issue", "connectivity issue",
            "unable to connect", "cannot connect to",
            "aws issue", "nile outage", "nile down",
        ],
    },
]

OTHER_CATEGORY = {"name": "Other", "color": "D9D9D9"}
ALL_CATS = [c["name"] for c in CATEGORIES] + [OTHER_CATEGORY["name"]]
CAT_COLOR = {cat["name"]: cat["color"] for cat in CATEGORIES}
CAT_COLOR[OTHER_CATEGORY["name"]] = OTHER_CATEGORY["color"]
